import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul className={styles.testlist}>
          {data.map((item) => (
            <li key="item.id">{item.title}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const data = [
    {
      id: 1,
      title: "title",
    },
    {
      id: 2,
      title: "another title",
    },
  ];

  return {
    props: {
      data,
    },
  };
}
